### ISSUE TITLE
Featured Images not updating when trying to update post from front end form

### ISSUE THREAD

**Issue by ChrisO2134** [pods-framework/pods-gravity-forms#77] opened 2017-07-27 11:23 UTC
When using a gravity form on a pod post page to update form fields, all text fields can be updated and saved over and over, however images can only be saved once, then all further image files get ignored so featured image cannot be updated.

**Comment by ChrisO2134** [comment] 2017-07-27 12:26
UPDATE: Issue seems to fix if using the 'File Upload' choice as form field in Gravity form rather than 'Post Image' field. I'm not clever enough to know why that is, but hope this info helps find the bug.

**Comment by sc0ttkclark** [comment] 2017-09-13 17:17
Please try the latest 1.4 I'm working on: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by jimtrue** [comment] 2018-06-09 14:07
Related to #75 Closing this as duplicate of that one. The Post Image field doesn't work, but any other image field should work just fine.

**Closed by jimtrue** 2018-06-09 14:07 UTC
Labels: duplicate
