### ISSUE TITLE
Uploaded File Using Gravity Form Does Not Attach to Pod Post

### ISSUE THREAD

**Issue by tokazama2** [pods-framework/pods-gravity-forms#85] opened 2017-09-08 18:12 UTC
Using Pods 2.7 rc1, Gravity forms 2.2.5, Pods Gravity Forms Add-on 1.3. 
I have been working on a gravity form. All fields are mapped and working with Pods, except the file upload. The files upload to my server, but not to the pod. I've been chasing my tail trying to figure this out.

- The Pod field, "resource_upload", is set with File Uploader: Upload and/or Select 
- The Gravity Form field, "Resource Upload" is set up using Post Fields>Custom Field>Field-Type=File Upload>Custom Field Name="resource_upload".
- Gravity Form Feed Setting: resource_upload is mapped to Resource Upload

[gravityforms-export-2017-09-08.zip](https://github.com/pods-framework/pods-gravity-forms/files/1288735/gravityforms-export-2017-09-08.zip)
[Pods Configuration Resources only.txt](https://github.com/pods-framework/pods-gravity-forms/files/1288750/Pods.Configuration.Resources.only.txt)
[Pods Configuration with all related taxonomy fields.txt](https://github.com/pods-framework/pods-gravity-forms/files/1288751/Pods.Configuration.with.all.related.taxonomy.fields.txt)
[Gravity Forms System Status Report.txt](https://github.com/pods-framework/pods-gravity-forms/files/1288749/Gravity.Forms.System.Status.Report.txt)

**Additional Information that may, or may not, be helpful:**
The site is not "live" right now.  I have to change my hosts file to work on the site.  
I have added the following to my child theme functions.php.  I disabled it, and this code doesn't seem to make any difference in my dilemma. 
```/*Member Documents Upload Path*/
add_filter( 'gform_upload_path_10', 'change_upload_path_10', 10, 2 );
function change_upload_path_10( $path_info, $form_id ) {
   $path_info['path'] = '/home/mysite.com/public_html/resources/_member/';
   $path_info['url'] = 'http://mysite.com/resources/_member/';
   return $path_info;
}

**Comment by tokazama2** [comment] 2017-09-08 18:19
I tried reverting back to Pods 2.6 and that does not solve the problem

**Comment by sc0ttkclark** [comment] 2017-09-13 17:14
Try the latest 1.4 I'm working on getting out: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by tokazama2** [comment] 2017-09-13 22:15
I did a quick test and it still isn't working.  I will play around with some settings, but may not be able to get to it until tonight.  

In the Gravity Forms Feed Settings, I see there is a new Custom Fields area.  Should I use that as opposed to the pods field mapping at the top of the page?  

Does it make any difference in the Pods Custom Field option the type of File Uploader I select?

**Comment by HBMBR** [comment] 2017-09-20 16:17
Hi i seem to be facing this problem, the issue is also extending to Multi-select as well.

**Comment by tokazama2** [comment] 2017-10-04 19:47
@sc0ttkclark Any luck on figuring this one out?  I would be happy to pay for this to be fixed.  :-)

**Comment by sc0ttkclark** [comment] 2017-10-04 19:55
I should have some more time this weekend, will take another crack at it. Feel free to donate to https://pods.io/friends-of-pods/ anyways :)

**Comment by tokazama2** [comment] 2017-10-04 22:19
@sc0ttkclark Done. Thanks!

**Comment by sc0ttkclark** [comment] 2017-10-10 15:06
Still looking into this for you @tokazama2

**Comment by jimtrue** [comment] 2017-10-27 17:08
@tokazama2 I checked the 2nd upload you provided and form and had no issues. I thought there might be a problem because the File Upload style was a PLUpload. Since the Processor settings don't come across on the JSON from Gravity Forms, I'm wondering if maybe that's where you're running into the problems.

I could not get your initial configuration and form to work properly. It never passed the document title over and while it uploaded the file, it didn't get transferred into that field. Can you provide a screenshot of your Pod Processor Settings for both forms? That will help us map your fields, properly.

@HBMBR Can you open a separate issue on the Multi-Select? We try to keep the issues if possible related to one issue and not spread them across to multiple areas.

**Comment by tokazama2** [comment] 2017-11-21 22:32
Sorry for the delay.  I was side-tracked by a different project. I created a new very simple pod with only one field (file upload) and a simple form (document title, file upload).  Please see attached applicable documents.

[Pods Configuration Export Results.txt](https://github.com/pods-framework/pods-gravity-forms/files/1493224/Pods.Configuration.Export.Results.txt)
[gravityforms-export-2017-11-21.zip](https://github.com/pods-framework/pods-gravity-forms/files/1493225/gravityforms-export-2017-11-21.zip)
[Gravity Forms System Status Report.txt](https://github.com/pods-framework/pods-gravity-forms/files/1493226/Gravity.Forms.System.Status.Report.txt)
![upload-test-feed-settings](https://user-images.githubusercontent.com/25513887/33100279-07ee9de2-ced1-11e7-8997-019508960b94.JPG)

**Comment by sc0ttkclark** [comment] 2018-06-08 11:29
Please try the latest 1.4 beta release: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by tokazama2** [comment] 2018-09-12 19:51
I have finally been able to get back to this project.  I am currently using pods v2.7.9.  The file is now uploading to the default upload folder (renamed to 'resources') and connecting to the custom post type.  I just wish I could upload to a certain directory.  I suspect that is a WordPress problem and not a Pods problem.  

I am using Gravity Forms with Pods.  I added the following code to the functions.php file: 
`add_filter( 'gform_upload_path_10', 'change_upload_path_10', 10, 2 );
function change_upload_path_10( $path_info, $form_id ) {
   $path_info['path'] = '/home/mysite.com/public_html/resources/_member/';
   $path_info['url'] = 'http://mysite.com/resources/_member/';
   return $path_info;
}`

Now the file uploads twice, once to the directory as specified in the code listed above and another copy into the main uploads folder.

At least Pods is working.  Thanks for your help!

**Comment by sc0ttkclark** [comment] 2018-10-09 17:05
Pods GF takes the media from Gravity Forms and adds it to the Media Library. This is likely why you see two. We don't have Pods-specific code for the upload handling, but there are hooks in WordPress itself that you might be able to find to accomplish the same thing.

**Closed** 2018-10-09 17:05 UTC
Labels: bug
