### ISSUE TITLE
Prefilling in edit form doesn't show file field data?

### ISSUE THREAD

**Issue by siy34** [pods-framework/pods-gravity-forms#87] opened 2017-10-10 23:01 UTC
Hi, I noticed when putting an edit form inside a singular pod page, the file field doesn't show existing files that have been previously uploaded to the pod. Is this a bug or a feature yet to be implemented?

**Comment by jimtrue** [comment] 2017-10-10 23:04
I'm not sure I follow what you mean by 'putting an edit form inside a singular pod page'. Can you clarify or provide a screen shot?

**Comment by jimtrue** [comment] 2017-10-10 23:06
If you're talking about the facility where it's supposed to load existing field content to edit the existing record, you are correct: images, file fields and I believe relationships do not populate at this time. This feature is in _progress_ but not fully functional, yet. I believe 1.4 should fix this, but would need @sc0ttkclark to clarify.

**Comment by siy34** [comment] 2017-10-11 02:40
Yes, that's exactly what I was asking about.  Thank you Jim for addressing it. I'll give 1.4 a try.

**Comment by siy34** [comment] 2017-10-11 02:50
Just tested with 1.4 pre-release. This feature doesn't seem to be in place yet.

**Comment by siy34** [comment] 2017-10-11 09:24
@sc0ttkclark Another field type that does not populate in the form to edit is multi-select related post.

**Comment by spiral-labs** [comment] 2018-05-27 09:10
Hi everyone! are there any updates? I'm new to Pods and just started using pods + gf but can't find the 1.4 was it released?, cheers!

**Comment by sc0ttkclark** [comment] 2018-06-08 10:54
Pods GF does not prepopulate file or address field types. I have pushed more fixes for it to support some other ones it didn't quite have support for.

**Comment by sc0ttkclark** [comment] 2018-06-08 10:55
I'm going to have to ping support to find out how to prepopulate something in the file field and how to prepopulate the address field values (based on mapping from individual pod fields to Address 1, Address 2, City, State, or Country.

**Comment by sc0ttkclark** [comment] 2018-10-16 18:57
1.4 introduces a fix that will not clear the file field value in the Pod item if the Gravity Form file field is empty. That's a temporary workaround here until we determine the best way to show that a file field has a file value on load.

**Comment by sc0ttkclark** [comment] 2018-10-16 19:00
Closing as duplicate of #87

**Closed by sc0ttkclark** 2018-10-16 19:00 UTC
Labels: enhancement
