### ISSUE TITLE
Gravity Forms Featured Image not being added to post upon submission

### ISSUE THREAD

**Issue by napa-web-designer** [pods-framework/pods-gravity-forms#90] opened 2017-12-12 18:42 UTC
I created a Gravity Forms form with a Post Image Field and mapped it as the Featured Image in my GF Pods settings. Then submitted post and although everything else seemed to work as expected, the Featured Image did not.

I recorded a video running through my settings as I was not sure exactly what would help and this way I could quickly show you everything I think you might want to know to replicate.

https://www.dropbox.com/s/z4kf21l7anp83hu/pods-featured-image-issue.mov?dl=0

**Here is the information on the Pods Admin>Settings page:**
Debug Information
WordPress Version: 4.9.1

PHP Version: 7.1.12

MySQL Version: 5.6.23

Server Software: LiteSpeed

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/studioi/public_html/cave2/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Companions of the Cave

Currently Active Plugins:

Akismet Anti-Spam: 4.0.1
Better Notifications for WordPress: 1.6.9
Duplicate Page: 2.4
Go Daddy Quick Setup: 1.04
Gravity Forms: 2.2.5.8
Limit Login Attempts: 1.7.1
List Custom Taxonomy Widget: 4.1
Login Logo Editor: 1.2.2
Paid Memberships Pro: 1.9.4.2
Pods - Custom Content Types and Fields: 2.7.1
Pods Gravity Forms Add-On: 1.3
Quick Page/Post Redirect Plugin: 5.1.8
Simple Audio Player: 0.2

**Comment by jimtrue** [comment] 2018-06-09 14:09
You cannot use Post Image field. You have to use a regular file upload field. Duplicate of #75

**Closed by jimtrue** 2018-06-09 14:09 UTC
Labels: duplicate
